"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Lang = "en" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Legacy top-level keys (Sidebar uses these)
    dashboard: "Dashboard",
    checkIn: "Check In",
    skills: "Skills",
    aiCoach: "AI Coach",
    events: "Events",
    history: "History",
    settings: "Settings",
    signOut: "Sign Out",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    arabic: "العربية",
    english: "English",

    // nav.*
    "nav.dashboard": "Dashboard",
    "nav.checkIn": "Check In",
    "nav.skills": "Skills",
    "nav.aiCoach": "AI Coach",
    "nav.events": "Events",
    "nav.history": "History",
    "nav.settings": "Settings",
    "nav.signOut": "Sign Out",

    // common.*
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.skip": "Skip",
    "common.continue": "Continue",
    "common.loading": "Loading...",
    "common.yes": "Yes",
    "common.no": "No",
    "common.back": "Back",
    "common.next": "Next",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.close": "Close",
    "common.open": "Open",
    "common.optional": "(optional)",

    // dashboard.*
    "dashboard.todayNote": "Today's note",
    "dashboard.recentPerformance": "Recent performance",
    "dashboard.coach": "Coach",
    "dashboard.openFullChat": "Open full chat →",
    "dashboard.messageCoach": "Message your coach…",
    "dashboard.observationInProgress": "Observation in Progress",
    "dashboard.noActiveSkill": "No Active Skill",
    "dashboard.skillOverview": "Skill Overview",
    "dashboard.observationMode": "You're in observation mode",
    "dashboard.talkToCoach": "Talk to coach",
    "dashboard.addPersonalStatement": "Add your personal statement…",
    "dashboard.currentPlan": "Current Plan",
    "dashboard.skillTree": "Skill tree",
    "dashboard.yourTask": "Your task",
    "dashboard.noTaskDefined": "No task defined yet",
    "dashboard.workingAround": "Working around:",
    "dashboard.setTaskInSkillPage": "set one in the skill page",
    "dashboard.dailyCheckIn": "Daily Check-In",
    "dashboard.completedToday": "Completed today",
    "dashboard.startCheckIn": "Start Check-In",
    "dashboard.last7days": "Last 7 days",
    "dashboard.7dAgo": "7d ago",
    "dashboard.today": "Today",
    "dashboard.upcomingEvents": "Upcoming Events",
    "dashboard.noUpcomingEvents": "No upcoming events",
    "dashboard.askCoachAnything": "Ask your coach anything…",

    // checkin.*
    "checkin.title": "Daily Check-In",
    "checkin.didYouStudy": "Did you study today?",
    "checkin.howWasFocus": "How was your focus?",
    "checkin.whyDidYouMiss": "Why did you miss?",
    "checkin.whatMethod": "What method did you use?",
    "checkin.anythingToNote": "Anything to note?",
    "checkin.quickReflection": "Quick reflection",
    "checkin.markAtypical": "Mark as atypical day (illness, travel, etc.)",
    "checkin.energy": "Energy",
    "checkin.mood": "Mood",
    "checkin.submitCheckIn": "Submit Check-In",
    "checkin.submitting": "Submitting...",
    "checkin.contextPlaceholder": "Quick context about your day...",
    "checkin.answerPlaceholder": "Your answer…",
    "checkin.skipAndSubmit": "Skip & Submit",
    "checkin.optional": "(optional)",
    "checkin.energyOptional": "Energy (optional)",
    "checkin.moodOptional": "Mood (optional)",
    "checkin.continueArrow": "Continue →",
    "checkin.whatHappened": "What happened?",
    "checkin.atypicalHint": "illness, travel, etc.",

    // focus options
    "checkin.focus.none": "None",
    "checkin.focus.brief": "Brief",
    "checkin.focus.focused": "Focused",
    "checkin.focus.deep": "Deep",
    "checkin.focus.noneDesc": "Didn't really focus",
    "checkin.focus.briefDesc": "A few minutes of focus",
    "checkin.focus.focusedDesc": "Solid focused block",
    "checkin.focus.deepDesc": "Extended deep focus",

    // miss reason options
    "checkin.miss.tooBusy": "Too busy",
    "checkin.miss.forgot": "Forgot",
    "checkin.miss.overwhelmed": "Felt overwhelmed",
    "checkin.miss.notInMood": "Wasn't in the mood",
    "checkin.miss.externalEvent": "External event",
    "checkin.miss.other": "Other",

    // study method options
    "checkin.method.explain": "Explained it out loud",
    "checkin.method.qa": "Practice questions / Q&A",
    "checkin.method.mindmap": "Mind map",
    "checkin.method.notes": "Wrote notes",
    "checkin.method.record": "Voice / video recording",
    "checkin.method.read": "Reading / watching",

    // decay options
    "checkin.decay.noLoss": "No loss",
    "checkin.decay.whenDropped": "When did focus drop?",

    // skills.*
    "skills.week1Label": "Week 1 — Stabilize",
    "skills.week2Label": "Week 2 — Express",
    "skills.week3Label": "Week 3 — Probe",
    "skills.week1Short": "Stabilize",
    "skills.week2Short": "Express",
    "skills.week3Short": "Probe",
    "skills.tier": "Tier",
    "skills.active": "Active",
    "skills.locked": "Locked",
    "skills.available": "Available",
    "skills.stable": "Stable",
    "skills.mastered": "Mastered",
    "skills.stability": "Stability",
    "skills.prerequisites": "Prerequisites",
    "skills.weekPhase": "Week Phase",
    "skills.cycleProgress": "Cycle Progress",
    "skills.stabilityScore": "Stability Score",
    "skills.yourTask": "Your task",
    "skills.notStarted": "Not Started",
    "skills.ready": "Ready",
    "skills.description": "Description",
    "skills.whyThisSkill": "Why This Skill?",
    "skills.trainingProgress": "Training Progress",
    "skills.checkIns": "Check-ins",
    "skills.daysStudied": "Days studied",
    "skills.focusedDays": "Focused days",
    "skills.finalStability": "Final stability",
    "skills.totalCheckIns": "Total check-ins",
    "skills.trainingTimeline": "Training timeline",
    "skills.defineTask": "Define your task (time/place/action)",
    "skills.setTask": "Set Task",
    "skills.saving": "Saving...",
    "skills.activating": "Activating...",
    "skills.activateSkill": "Activate This Skill",
    "skills.backToSkillTree": "Back to Skill Tree",
    "skills.requiredToUnlock": "Required to unlock",
    "skills.completeFirst": "Complete first",
    "skills.requires": "Requires",
    "skills.unlocks": "Unlocks",
    "skills.viewFullDetails": "View full details",
    "skills.whyThisSkillLabel": "Why this skill?",
    "skills.status": "Status",
    "skills.week": "Week",
    "skills.taskUsed": "Task used",
    "skills.prerequisiteNote": "Each prerequisite must reach Stable — completed by going through its 3-week training cycle with a stability score of 70% or above. Progress is based on your check-in patterns.",
    "skills.skillIsLocked": "This skill is locked",
    "skills.needsPlanning": "← needs Planning first",

    // chat.*
    "chat.placeholder": "Send a message...",
    "chat.send": "Send",
    "chat.title": "Chat with your AI study coach",
    "chat.askCoach": "Ask your study coach...",
    "chat.aiStudyCoach": "Your AI study coach",
    "chat.coachDescription": "Ask about your progress, get advice on your active skill, or just talk about how studying is going.",

    // events.*
    "events.addEvent": "Add Event",
    "events.eventName": "Event name",
    "events.type": "Type",
    "events.date": "Date",
    "events.noUpcoming": "No upcoming events",
    "events.upcoming": "Upcoming",
    "events.passed": "Passed",
    "events.upcomingEvents": "Upcoming Events",
    "events.daysAway": "days away",
    "events.today": "Today",
    "events.tomorrow": "Tomorrow",
    "events.exam": "exam",
    "events.quiz": "quiz",
    "events.deadline": "deadline",
    "events.project": "project",
    "events.other": "other",
    "events.loadingEvents": "Loading events...",
    "events.title": "Events",
    "events.add": "Add",
    "events.cancel": "Cancel",
    "events.namePlaceholder": "e.g., Final Exam",

    // history.*
    "history.title": "Study History",
    "history.studied": "Studied",
    "history.missed": "Missed",
    "history.focused": "Focused",
    "history.checkInHistory": "Check-In History",
    "history.trackPatterns": "Track your study patterns over time.",
    "history.checkIns30d": "Check-ins (30d)",
    "history.daysStudied": "Days studied",
    "history.focusedPlusDays": "Focused+ days",
    "history.noFocus": "No focus",
    "history.brief": "Brief",
    "history.deep": "Deep",
    "history.focusLevel": "Focus Level",
    "history.focusDecay": "Focus Decay",
    "history.energy": "Energy",
    "history.mood": "Mood",
    "history.note": "Note",
    "history.atypical": "Atypical",
    "history.backfilled": "Backfilled",

    // settings.*
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.name": "Name",
    "settings.notSet": "Not set",
    "settings.actions": "Actions",
    "settings.appearance": "Appearance",
    "settings.accentColor": "Accent color",
    "settings.saving": "Saving…",
    "settings.signOut": "Sign Out",

    // auth.*
    "auth.signInToAccount": "Sign in to your account",
    "auth.emailAddress": "Email address",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.createAccount": "Create account",
    "auth.fullName": "Full name",
    "auth.forgotPassword": "Forgot password?",
    "auth.resetPassword": "Reset Password",
    "auth.sendResetLink": "Send Reset Link",
    "auth.backToSignIn": "Back to sign in",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signUp": "Sign up",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    "auth.sending": "Sending...",
    "auth.welcomeBack": "Welcome Back",
    "auth.continueJourney": "Sign in to continue your study journey",
    "auth.startHabits": "Start building better study habits",
    "auth.email": "Email",
    "auth.name": "Name",
    "auth.rememberMe": "Remember me",
    "auth.noAccount": "No account?",
    "auth.register": "Register",
    "auth.alreadyHaveAccountQ": "Already have an account?",
    "auth.signInLink": "Sign in",
    "auth.checkEmailForReset": "Check your email for a reset link",
    "auth.enterEmailForReset": "Enter your email to receive a password reset link",
    "auth.resetLinkSent": "If an account with that email exists, we sent a reset link.",
    "auth.resendEmail": "Resend email",
    "auth.backToLogin": "Back to login",
    "auth.invalidCredentials": "Invalid email or password",

    // plan card instructions
    "plan.week1Instruction": "Focus only on showing up consistently. Don't push for perfection — build the routine first.",
    "plan.week2Instruction": "You've shown up. Now pay attention to quality. Try small tweaks to how you apply the skill.",
    "plan.week3Instruction": "Push the skill into harder situations. Notice when it breaks down — that's useful data, not failure.",

    // phase / observation
    "phase.observation": "Observation Phase",
    "phase.skill_training": "Skill Training",
    "phase.onboarding": "Onboarding",
    "phase.day": "Day",
    "phase.activeLabel": "Active:",
    "phase.checkIns": "check-ins",
    "phase.completeCheckIns": "complete your daily check-ins",
  },
  ar: {
    // Legacy top-level keys (Sidebar uses these)
    dashboard: "لوحة التحكم",
    checkIn: "تسجيل اليوم",
    skills: "المهارات",
    aiCoach: "المدرب الذكي",
    events: "الأحداث",
    history: "السجل",
    settings: "الإعدادات",
    signOut: "تسجيل الخروج",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    arabic: "العربية",
    english: "English",

    // nav.*
    "nav.dashboard": "لوحة التحكم",
    "nav.checkIn": "تسجيل اليوم",
    "nav.skills": "المهارات",
    "nav.aiCoach": "المدرب الذكي",
    "nav.events": "الأحداث",
    "nav.history": "السجل",
    "nav.settings": "الإعدادات",
    "nav.signOut": "تسجيل الخروج",

    // common.*
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.submit": "إرسال",
    "common.skip": "تخطي",
    "common.continue": "متابعة",
    "common.loading": "جاري التحميل...",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.add": "إضافة",
    "common.close": "إغلاق",
    "common.open": "فتح",
    "common.optional": "(اختياري)",

    // dashboard.*
    "dashboard.todayNote": "ملاحظة اليوم",
    "dashboard.recentPerformance": "الأداء الأخير",
    "dashboard.coach": "المدرب",
    "dashboard.openFullChat": "فتح المحادثة الكاملة",
    "dashboard.messageCoach": "أرسل رسالة لمدربك",
    "dashboard.observationInProgress": "المراقبة جارية",
    "dashboard.noActiveSkill": "لا توجد مهارة نشطة",
    "dashboard.skillOverview": "نظرة عامة على المهارات",
    "dashboard.observationMode": "أنت في وضع المراقبة",
    "dashboard.talkToCoach": "تحدث مع المدرب",
    "dashboard.addPersonalStatement": "أضف تأكيدك الشخصي",
    "dashboard.currentPlan": "الخطة الحالية",
    "dashboard.skillTree": "شجرة المهارات",
    "dashboard.yourTask": "مهمتك",
    "dashboard.noTaskDefined": "لم يتم تحديد مهمة بعد",
    "dashboard.workingAround": "التحديات:",
    "dashboard.setTaskInSkillPage": "حددها في صفحة المهارات",
    "dashboard.dailyCheckIn": "تسجيل اليومي",
    "dashboard.completedToday": "تم اليوم",
    "dashboard.startCheckIn": "ابدأ التسجيل",
    "dashboard.last7days": "آخر 7 أيام",
    "dashboard.7dAgo": "منذ 7 أيام",
    "dashboard.today": "اليوم",
    "dashboard.upcomingEvents": "الأحداث القادمة",
    "dashboard.noUpcomingEvents": "لا توجد أحداث قادمة",
    "dashboard.askCoachAnything": "اسأل مدربك أي شيء…",

    // checkin.*
    "checkin.title": "تسجيل اليومي",
    "checkin.didYouStudy": "هل درست اليوم؟",
    "checkin.howWasFocus": "كيف كان تركيزك؟",
    "checkin.whyDidYouMiss": "لماذا فاتك الدراسة؟",
    "checkin.whatMethod": "ما الطريقة التي استخدمتها؟",
    "checkin.anythingToNote": "هل هناك ما تريد ملاحظته؟",
    "checkin.quickReflection": "تأمل سريع",
    "checkin.markAtypical": "وضع علامة على يوم غير عادي (مرض، سفر، إلخ)",
    "checkin.energy": "الطاقة",
    "checkin.mood": "المزاج",
    "checkin.submitCheckIn": "إرسال التسجيل",
    "checkin.submitting": "جاري الإرسال...",
    "checkin.contextPlaceholder": "سياق سريع عن يومك...",
    "checkin.answerPlaceholder": "إجابتك...",
    "checkin.skipAndSubmit": "تخطي وإرسال",
    "checkin.optional": "(اختياري)",
    "checkin.energyOptional": "الطاقة (اختياري)",
    "checkin.moodOptional": "المزاج (اختياري)",
    "checkin.continueArrow": "متابعة ←",
    "checkin.whatHappened": "ماذا حدث؟",
    "checkin.atypicalHint": "مرض، سفر، إلخ",

    // focus options
    "checkin.focus.none": "لا يوجد",
    "checkin.focus.brief": "مختصر",
    "checkin.focus.focused": "مركّز",
    "checkin.focus.deep": "عميق",
    "checkin.focus.noneDesc": "لم أركز فعلاً",
    "checkin.focus.briefDesc": "بضع دقائق تركيز",
    "checkin.focus.focusedDesc": "كتلة تركيز جيدة",
    "checkin.focus.deepDesc": "تركيز عميق ممتد",

    // miss reason options
    "checkin.miss.tooBusy": "مشغول جداً",
    "checkin.miss.forgot": "نسيت",
    "checkin.miss.overwhelmed": "شعرت بالإرهاق",
    "checkin.miss.notInMood": "لم أكن في المزاج",
    "checkin.miss.externalEvent": "حدث خارجي",
    "checkin.miss.other": "أخرى",

    // study method options
    "checkin.method.explain": "شرحته بصوت عالٍ",
    "checkin.method.qa": "أسئلة تدريبية / سؤال وجواب",
    "checkin.method.mindmap": "خريطة ذهنية",
    "checkin.method.notes": "كتبت ملاحظات",
    "checkin.method.record": "تسجيل صوتي / فيديو",
    "checkin.method.read": "قراءة / مشاهدة",

    // decay options
    "checkin.decay.noLoss": "لا انخفاض",
    "checkin.decay.whenDropped": "متى انخفض تركيزك؟",

    // skills.*
    "skills.week1Label": "الأسبوع 1 — استقرار",
    "skills.week2Label": "الأسبوع 2 — تعبير",
    "skills.week3Label": "الأسبوع 3 — استكشاف",
    "skills.week1Short": "استقرار",
    "skills.week2Short": "تعبير",
    "skills.week3Short": "استكشاف",
    "skills.tier": "المستوى",
    "skills.active": "نشط",
    "skills.locked": "مقفل",
    "skills.available": "متاح",
    "skills.stable": "مستقر",
    "skills.mastered": "متقن",
    "skills.stability": "الاستقرار",
    "skills.prerequisites": "المتطلبات",
    "skills.weekPhase": "مرحلة الأسبوع",
    "skills.cycleProgress": "تقدم الدورة",
    "skills.stabilityScore": "درجة الاستقرار",
    "skills.yourTask": "مهمتك",
    "skills.notStarted": "لم يبدأ",
    "skills.ready": "جاهز",
    "skills.description": "الوصف",
    "skills.whyThisSkill": "لماذا هذه المهارة؟",
    "skills.trainingProgress": "تقدم التدريب",
    "skills.checkIns": "تسجيلات",
    "skills.daysStudied": "أيام الدراسة",
    "skills.focusedDays": "أيام التركيز",
    "skills.finalStability": "الاستقرار النهائي",
    "skills.totalCheckIns": "مجموع التسجيلات",
    "skills.trainingTimeline": "الجدول الزمني للتدريب",
    "skills.defineTask": "حدد مهمتك (وقت / مكان / فعل)",
    "skills.setTask": "تعيين المهمة",
    "skills.saving": "جاري الحفظ...",
    "skills.activating": "جاري التفعيل...",
    "skills.activateSkill": "تفعيل هذه المهارة",
    "skills.backToSkillTree": "العودة إلى شجرة المهارات",
    "skills.requiredToUnlock": "مطلوب لفتح القفل",
    "skills.completeFirst": "أكمل أولاً",
    "skills.requires": "يتطلب",
    "skills.unlocks": "يفتح",
    "skills.viewFullDetails": "عرض التفاصيل الكاملة",
    "skills.whyThisSkillLabel": "لماذا هذه المهارة؟",
    "skills.status": "الحالة",
    "skills.week": "الأسبوع",
    "skills.taskUsed": "المهمة المستخدمة",
    "skills.prerequisiteNote": "يجب أن يصل كل متطلب إلى مستقر — مكتمل بالمرور بدورة التدريب المكونة من 3 أسابيع بدرجة استقرار 70٪ أو أعلى. يعتمد التقدم على أنماط تسجيلاتك.",
    "skills.skillIsLocked": "هذه المهارة مقفلة",
    "skills.needsPlanning": "← يحتاج التخطيط أولاً",

    // chat.*
    "chat.placeholder": "أرسل رسالة...",
    "chat.send": "إرسال",
    "chat.title": "تحدث مع مدربك الذكي للدراسة",
    "chat.askCoach": "اسأل مدربك للدراسة...",
    "chat.aiStudyCoach": "مدربك الذكي للدراسة",
    "chat.coachDescription": "اسأل عن تقدمك، واحصل على نصائح حول مهارتك النشطة، أو تحدث عن كيفية سير الدراسة.",

    // events.*
    "events.addEvent": "إضافة حدث",
    "events.eventName": "اسم الحدث",
    "events.type": "النوع",
    "events.date": "التاريخ",
    "events.noUpcoming": "لا توجد أحداث قادمة",
    "events.upcoming": "القادمة",
    "events.passed": "المنتهية",
    "events.upcomingEvents": "الأحداث القادمة",
    "events.daysAway": "أيام متبقية",
    "events.today": "اليوم",
    "events.tomorrow": "غداً",
    "events.exam": "امتحان",
    "events.quiz": "اختبار",
    "events.deadline": "موعد نهائي",
    "events.project": "مشروع",
    "events.other": "أخرى",
    "events.loadingEvents": "جاري تحميل الأحداث...",
    "events.title": "الأحداث",
    "events.add": "إضافة",
    "events.cancel": "إلغاء",
    "events.namePlaceholder": "مثال: الامتحان النهائي",

    // history.*
    "history.title": "سجل الدراسة",
    "history.studied": "درست",
    "history.missed": "فاتني",
    "history.focused": "مركّز",
    "history.checkInHistory": "سجل التسجيلات",
    "history.trackPatterns": "تتبع أنماط دراستك عبر الزمن.",
    "history.checkIns30d": "التسجيلات (30 يوم)",
    "history.daysStudied": "أيام الدراسة",
    "history.focusedPlusDays": "أيام التركيز+",
    "history.noFocus": "لا تركيز",
    "history.brief": "مختصر",
    "history.deep": "عميق",
    "history.focusLevel": "مستوى التركيز",
    "history.focusDecay": "انخفاض التركيز",
    "history.energy": "الطاقة",
    "history.mood": "المزاج",
    "history.note": "ملاحظة",
    "history.atypical": "غير عادي",
    "history.backfilled": "مُعبأ لاحقاً",

    // settings.*
    "settings.title": "الإعدادات",
    "settings.account": "الحساب",
    "settings.email": "البريد الإلكتروني",
    "settings.name": "الاسم",
    "settings.notSet": "غير محدد",
    "settings.actions": "الإجراءات",
    "settings.appearance": "المظهر",
    "settings.accentColor": "لون التمييز",
    "settings.saving": "جاري الحفظ…",
    "settings.signOut": "تسجيل الخروج",

    // auth.*
    "auth.signInToAccount": "سجّل الدخول إلى حسابك",
    "auth.emailAddress": "عنوان البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.signIn": "تسجيل الدخول",
    "auth.createAccount": "إنشاء حساب",
    "auth.fullName": "الاسم الكامل",
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.resetPassword": "إعادة تعيين كلمة المرور",
    "auth.sendResetLink": "إرسال رابط الإعادة",
    "auth.backToSignIn": "العودة إلى تسجيل الدخول",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.signUp": "التسجيل",
    "auth.signingIn": "جاري تسجيل الدخول...",
    "auth.creatingAccount": "جاري إنشاء الحساب...",
    "auth.sending": "جاري الإرسال...",
    "auth.welcomeBack": "مرحباً بعودتك",
    "auth.continueJourney": "سجّل دخولك لمتابعة رحلتك الدراسية",
    "auth.startHabits": "ابدأ في بناء عادات دراسية أفضل",
    "auth.email": "البريد الإلكتروني",
    "auth.name": "الاسم",
    "auth.rememberMe": "تذكرني",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.register": "التسجيل",
    "auth.alreadyHaveAccountQ": "لديك حساب بالفعل؟",
    "auth.signInLink": "تسجيل الدخول",
    "auth.checkEmailForReset": "تحقق من بريدك الإلكتروني لرابط الإعادة",
    "auth.enterEmailForReset": "أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور",
    "auth.resetLinkSent": "إذا كان الحساب موجوداً، فقد أرسلنا رابط الإعادة.",
    "auth.resendEmail": "إعادة إرسال البريد",
    "auth.backToLogin": "العودة إلى تسجيل الدخول",
    "auth.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",

    // plan card instructions
    "plan.week1Instruction": "ركّز فقط على الحضور المنتظم. لا تسعَ للكمال — ابنِ الروتين أولاً.",
    "plan.week2Instruction": "لقد حضرت. الآن انتبه للجودة. جرّب تعديلات صغيرة في تطبيق المهارة.",
    "plan.week3Instruction": "طبّق المهارة في مواقف أصعب. لاحظ متى تنهار — هذا بيانات مفيدة، ليس فشلاً.",

    // phase / observation
    "phase.observation": "مرحلة المراقبة",
    "phase.skill_training": "تدريب المهارات",
    "phase.onboarding": "الإعداد",
    "phase.day": "يوم",
    "phase.activeLabel": "نشط:",
    "phase.checkIns": "تسجيلات",
    "phase.completeCheckIns": "أكمل تسجيلاتك اليومية",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Lang | null;
    if (saved === "ar" || saved === "en") {
      applyLang(saved);
      setLangState(saved);
    }
  }, []);

  const applyLang = (l: Lang) => {
    document.documentElement.lang = l;
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
  };

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
    applyLang(l);
  };

  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
