"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Lang = "en" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Legacy top-level keys (Sidebar uses these)
    dashboard: "Dashboard",
    checkIn: "Check In",
    skills: "Skills",
    aiCoach: "AI Coach",
    tools: "AI Tools",
    events: "Events",
    history: "History",
    settings: "Settings",
    signOut: "Sign Out",
    "feedback.button": "Send Feedback",
    "feedback.title": "Send Feedback",
    "feedback.description": "Have a suggestion, found a bug, or just want to say something? We read everything.",
    "feedback.placeholder": "Write your feedback here…",
    "feedback.submit": "Send",
    "feedback.sending": "Sending…",
    "feedback.sent": "Feedback sent — thank you!",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    arabic: "العربية",
    english: "English",

    // nav.*
    "nav.dashboard": "Dashboard",
    "nav.checkIn": "Check In",
    "nav.skills": "Skills",
    "nav.aiCoach": "AI Coach",
    "nav.events": "Events",
    "nav.history": "History",
    "nav.settings": "Settings",
    "nav.signOut": "Sign Out",

    // common.*
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.skip": "Skip",
    "common.continue": "Continue",
    "common.loading": "Loading...",
    "common.yes": "Yes",
    "common.no": "No",
    "common.back": "Back",
    "common.next": "Next",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.close": "Close",
    "common.open": "Open",
    "common.optional": "(optional)",

    // dashboard.*
    "dashboard.todayNote": "Today's note",
    "dashboard.recentPerformance": "Recent performance",
    "dashboard.coach": "Coach",
    "dashboard.openFullChat": "Open full chat →",
    "dashboard.messageCoach": "Message your coach…",
    "dashboard.observationInProgress": "Observation in Progress",
    "dashboard.noActiveSkill": "No Active Skill",
    "dashboard.skillOverview": "Skill Overview",
    "dashboard.observationMode": "You're in observation mode",
    "dashboard.talkToCoach": "Talk to coach",
    "dashboard.addPersonalStatement": "Add your personal statement…",
    "dashboard.currentPlan": "Current Plan",
    "dashboard.skillTree": "Skill tree",
    "dashboard.yourTask": "Your task",
    "dashboard.noTaskDefined": "No task defined yet",
    "dashboard.workingAround": "Working around:",
    "dashboard.setTaskInSkillPage": "set one in the skill page",
    "dashboard.dailyCheckIn": "Daily Check-In",
    "dashboard.completedToday": "Completed today",
    "dashboard.startCheckIn": "Start Check-In",
    "dashboard.last7days": "Last 7 days",
    "dashboard.7dAgo": "7d ago",
    "dashboard.today": "Today",
    "dashboard.upcomingEvents": "Upcoming Events",
    "dashboard.noUpcomingEvents": "No upcoming events",
    "dashboard.askCoachAnything": "Ask your coach anything…",

    // checkin.*
    "checkin.title": "Daily Check-In",
    "checkin.didYouStudy": "Did you study today?",
    "checkin.howWasFocus": "How was your focus?",
    "checkin.whyDidYouMiss": "Why did you miss?",
    "checkin.whatMethod": "What method did you use?",
    "checkin.anythingToNote": "Anything to note?",
    "checkin.quickReflection": "Quick reflection",
    "checkin.markAtypical": "Mark as atypical day (illness, travel, etc.)",
    "checkin.energy": "Energy",
    "checkin.mood": "Mood",
    "checkin.submitCheckIn": "Submit Check-In",
    "checkin.submitting": "Submitting...",
    "checkin.contextPlaceholder": "Quick context about your day...",
    "checkin.answerPlaceholder": "Your answer…",
    "checkin.skipAndSubmit": "Skip & Submit",
    "checkin.optional": "(optional)",
    "checkin.energyOptional": "Energy (optional)",
    "checkin.moodOptional": "Mood (optional)",
    "checkin.continueArrow": "Continue →",
    "checkin.whatHappened": "What happened?",
    "checkin.atypicalHint": "illness, travel, etc.",

    // focus options
    "checkin.focus.none": "None",
    "checkin.focus.brief": "Brief",
    "checkin.focus.focused": "Focused",
    "checkin.focus.deep": "Deep",
    "checkin.focus.noneDesc": "Didn't really focus",
    "checkin.focus.briefDesc": "A few minutes of focus",
    "checkin.focus.focusedDesc": "Solid focused block",
    "checkin.focus.deepDesc": "Extended deep focus",

    // miss reason options
    "checkin.miss.tooBusy": "Too busy",
    "checkin.miss.forgot": "Forgot",
    "checkin.miss.overwhelmed": "Felt overwhelmed",
    "checkin.miss.notInMood": "Wasn't in the mood",
    "checkin.miss.externalEvent": "External event",
    "checkin.miss.other": "Other",

    // study method options
    "checkin.method.explain": "Explained it out loud",
    "checkin.method.qa": "Practice questions / Q&A",
    "checkin.method.mindmap": "Mind map",
    "checkin.method.notes": "Wrote notes",
    "checkin.method.record": "Voice / video recording",
    "checkin.method.read": "Reading / watching",

    // decay options
    "checkin.decay.noLoss": "No loss",
    "checkin.decay.whenDropped": "When did focus drop?",

    // skills.*
    "skills.week1Label": "Week 1 — Stabilize",
    "skills.week2Label": "Week 2 — Express",
    "skills.week3Label": "Week 3 — Probe",
    "skills.week1Short": "Stabilize",
    "skills.week2Short": "Express",
    "skills.week3Short": "Probe",
    "skills.tier": "Tier",
    "skills.active": "Active",
    "skills.locked": "Locked",
    "skills.available": "Available",
    "skills.stable": "Stable",
    "skills.mastered": "Mastered",
    "skills.stability": "Stability",
    "skills.prerequisites": "Prerequisites",
    "skills.weekPhase": "Week Phase",
    "skills.cycleProgress": "Cycle Progress",
    "skills.stabilityScore": "Stability Score",
    "skills.yourTask": "Your task",
    "skills.notStarted": "Not Started",
    "skills.ready": "Ready",
    "skills.description": "Description",
    "skills.whyThisSkill": "Why This Skill?",
    "skills.trainingProgress": "Training Progress",
    "skills.checkIns": "Check-ins",
    "skills.daysStudied": "Days studied",
    "skills.focusedDays": "Focused days",
    "skills.finalStability": "Final stability",
    "skills.totalCheckIns": "Total check-ins",
    "skills.generateNarrative": "Generate growth summary",
    "skills.narrativeGenerating": "Generating...",
    "skills.narrativeError": "Could not generate summary. Try again.",
    "skills.trainingTimeline": "Training timeline",
    "skills.defineTask": "Define your task (time/place/action)",
    "skills.setTask": "Set Task",
    "skills.saving": "Saving...",
    "skills.activating": "Activating...",
    "skills.activateSkill": "Activate This Skill",
    "skills.backToSkillTree": "Back to Skill Tree",
    "skills.requiredToUnlock": "Required to unlock",
    "skills.completeFirst": "Complete first",
    "skills.requires": "Requires",
    "skills.unlocks": "Unlocks",
    "skills.viewFullDetails": "View full details",
    "skills.whyThisSkillLabel": "Why this skill?",
    "skills.status": "Status",
    "skills.week": "Week",
    "skills.taskUsed": "Task used",
    "skills.prerequisiteNote": "Each prerequisite must reach Stable — completed by going through its 3-week training cycle with a stability score of 70% or above. Progress is based on your check-in patterns.",
    "skills.skillIsLocked": "This skill is locked",
    "skills.needsPlanning": "← needs Planning first",

    // chat.*
    "chat.placeholder": "Send a message...",
    "chat.send": "Send",
    "chat.title": "Chat with your AI study coach",
    "chat.askCoach": "Ask your study coach...",
    "chat.aiStudyCoach": "Your AI study coach",
    "chat.coachDescription": "Ask about your progress, get advice on your active skill, or just talk about how studying is going.",

    // events.*
    "events.addEvent": "Add Event",
    "events.eventName": "Event name",
    "events.type": "Type",
    "events.date": "Date",
    "events.noUpcoming": "No upcoming events",
    "events.upcoming": "Upcoming",
    "events.passed": "Passed",
    "events.upcomingEvents": "Upcoming Events",
    "events.daysAway": "days away",
    "events.today": "Today",
    "events.tomorrow": "Tomorrow",
    "events.exam": "exam",
    "events.quiz": "quiz",
    "events.deadline": "deadline",
    "events.project": "project",
    "events.other": "other",
    "events.loadingEvents": "Loading events...",
    "events.title": "Events",
    "events.add": "Add",
    "events.cancel": "Cancel",
    "events.namePlaceholder": "e.g., Final Exam",

    // history.*
    "history.title": "Study History",
    "history.studied": "Studied",
    "history.missed": "Missed",
    "history.focused": "Focused",
    "history.checkInHistory": "Check-In History",
    "history.trackPatterns": "Track your study patterns over time.",
    "history.checkIns30d": "Check-ins (30d)",
    "history.daysStudied": "Days studied",
    "history.focusedPlusDays": "Focused+ days",
    "history.noFocus": "No focus",
    "history.brief": "Brief",
    "history.deep": "Deep",
    "history.focusLevel": "Focus Level",
    "history.focusDecay": "Focus Decay",
    "history.energy": "Energy",
    "history.mood": "Mood",
    "history.note": "Note",
    "history.atypical": "Atypical",
    "history.backfilled": "Backfilled",

    // settings.*
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.name": "Name",
    "settings.notSet": "Not set",
    "settings.actions": "Actions",
    "settings.appearance": "Appearance",
    "settings.accentColor": "Accent color",
    "settings.saving": "Saving…",
    "settings.signOut": "Sign Out",

    // auth.*
    "auth.signInToAccount": "Sign in to your account",
    "auth.emailAddress": "Email address",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.createAccount": "Create account",
    "auth.fullName": "Full name",
    "auth.forgotPassword": "Forgot password?",
    "auth.resetPassword": "Reset Password",
    "auth.sendResetLink": "Send Reset Link",
    "auth.backToSignIn": "Back to sign in",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signUp": "Sign up",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    "auth.sending": "Sending...",
    "auth.welcomeBack": "Welcome Back",
    "auth.continueJourney": "Sign in to continue your study journey",
    "auth.startHabits": "Start building better study habits",
    "auth.email": "Email",
    "auth.name": "Name",
    "auth.rememberMe": "Remember me",
    "auth.noAccount": "No account?",
    "auth.register": "Register",
    "auth.alreadyHaveAccountQ": "Already have an account?",
    "auth.signInLink": "Sign in",
    "auth.checkEmailForReset": "Check your email for a reset link",
    "auth.enterEmailForReset": "Enter your email to receive a password reset link",
    "auth.resetLinkSent": "If an account with that email exists, we sent a reset link.",
    "auth.resendEmail": "Resend email",
    "auth.backToLogin": "Back to login",
    "auth.invalidCredentials": "Invalid email or password",

    // onboarding.*
    "onboarding.studyGoalTitle": "What are you working toward?",
    "onboarding.studyGoalLabel": "Your study goal",
    "onboarding.studyGoalPlaceholder": "e.g., Pass organic chemistry, improve GPA...",
    "onboarding.hoursLabel": "How many hours do you typically study per day?",
    "onboarding.hoursPlaceholder": "e.g., 2",
    "onboarding.challengesTitle": "What trips you up most?",
    "onboarding.challengesSubtitle": "Select all that apply.",
    "onboarding.challengePlaceholder": "Describe your challenge...",
    "onboarding.timeTitle": "When do you usually study?",
    "onboarding.eventTitle": "Upcoming academic event",
    "onboarding.eventSubtitle": "Add an exam, quiz, or deadline to anchor your training.",
    "onboarding.eventNameLabel": "Event name",
    "onboarding.eventNamePlaceholder": "e.g., Midterm Exam",
    "onboarding.eventDateLabel": "Date",
    "onboarding.eventTypeLabel": "Type",
    "onboarding.startObservation": "Start Observation Phase",
    "onboarding.settingUp": "Setting up...",
    "onboarding.skipEvent": "Skip event for now",
    "onboarding.back": "Back",
    "onboarding.challenge.starting": "Starting is the hardest part",
    "onboarding.challenge.distracted": "I get distracted easily",
    "onboarding.challenge.nothingSticks": "I study but nothing sticks",
    "onboarding.challenge.cantFocus": "I can't focus for long",
    "onboarding.challenge.procrastinate": "I procrastinate until the last minute",
    "onboarding.challenge.dontKnowWhat": "I don't know what to study first",
    "onboarding.challenge.other": "Other",
    "onboarding.time.earlyMorning": "Early morning",
    "onboarding.time.lateMorning": "Late morning",
    "onboarding.time.afternoon": "Afternoon",
    "onboarding.time.evening": "Evening",
    "onboarding.time.lateNight": "Late night",
    "onboarding.time.varies": "Varies day to day",

    // dashboard extra strings
    "dashboard.observationText": "Study as you normally would and log your daily check-ins. After 5+ check-ins we'll unlock your first skill.\nIf you're noticing patterns — distractions, low energy, trouble starting — talk to your coach about them now.",
    "dashboard.completeCheckins": "Complete your daily check-ins. After 5+ check-ins in 7 days, you'll unlock your first skill.",
    "dashboard.visitSkillsPage": "You haven't activated a skill yet. Head to the Skills page, pick one, and activate it to start training.",

    // chat errors
    "chat.errorSend": "Failed to send message",
    "chat.errorFallback": "Sorry, something went wrong. Please try again.",

    // notifications
    "notifications.title": "Notifications",
    "notifications.allCaughtUp": "All caught up",
    "notifications.pushEnable": "Enable push notifications",
    "notifications.pushDisable": "Disable push notifications",
    "notifications.pushDenied": "Push notifications blocked in browser settings",
    "notifications.pushLoading": "Updating…",

    // dimension profile
    "dimension.profileTitle": "Skill Dimensions",
    "dimension.behavioral": "Behavioral",
    "dimension.cognitive": "Cognitive",
    "dimension.metacognitive": "Metacognitive",
    "dimension.notYet": "Not yet trained",
    "dimension.early": "Just started",
    "dimension.developing": "Developing",
    "dimension.strong": "Strong",
    "dimension.mastered": "Mastered",
    "dimension.whatAreThese": "What are these?",
    "dimension.behavioralDesc": "Whether you show up. Skills: Task Clarity, Initiation.",
    "dimension.cognitiveDesc": "What happens during a session — focus depth and environment management. Skills: Focus Containment, Environment Control, Focus Endurance, Cognitive Recovery.",
    "dimension.metacognitiveDesc": "How you plan before and reflect after. Skills: Planning & Sequencing, Deadline Calibration.",

    // banner
    "dashboard.addBannerPhoto": "Add a banner photo",
    "dashboard.bannerUrlPlaceholder": "Paste image URL...",
    "dashboard.removeBanner": "Remove",
    "dashboard.repositionBanner": "Reposition photo",
    "dashboard.dragToReposition": "Drag to reposition",
    "dashboard.savePosition": "Save position",
    "dashboard.personalStatementPlaceholder": "Your personal statement…",

    // backfill
    "checkin.differentDay": "Different day?",
    "checkin.checkingInFor": "Checking in for:",
    "checkin.today": "Today",
    "checkin.yesterday": "Yesterday",
    "checkin.twoDaysAgo": "2 days ago",
    "checkin.threeDaysAgo": "3 days ago",
    "checkin.alreadyCheckedIn": "You've already checked in for this day.",
    "checkin.fullSession": "Yes, full session",
    "checkin.briefly": "Briefly (< 15 min)",
    "checkin.intentionLabel": "What do you plan to study?",
    "checkin.intentionPlaceholder": "e.g. Chapter 3 summary, 30 min...",
    "checkin.intentionSkip": "Skip",

    // plan card instructions
    "plan.week1Instruction": "Focus only on showing up consistently. Don't push for perfection — build the routine first.",
    "plan.week2Instruction": "You've shown up. Now pay attention to quality. Try small tweaks to how you apply the skill.",
    "plan.week3Instruction": "Push the skill into harder situations. Notice when it breaks down — that's useful data, not failure.",

    // phase / observation
    "phase.observation": "Observation Phase",
    "phase.skill_training": "Skill Training",
    "phase.onboarding": "Onboarding",
    "phase.day": "Day",
    "phase.activeLabel": "Active:",
    "phase.checkIns": "check-ins",
    "phase.completeCheckIns": "complete your daily check-ins",

    // skill tree — tier labels
    "skills.tier.1": "Foundation",
    "skills.tier.2": "Structure",
    "skills.tier.3": "Endurance",
    "skills.tier.4": "Mastery",

    // skill tree — skill names (keyed by slug for DB-independent translation)
    "skills.name.task-clarity": "Task Clarity",
    "skills.name.initiation": "Initiation",
    "skills.name.focus-containment": "Focus Containment",
    "skills.name.environment-control": "Environment Control",
    "skills.name.focus-endurance": "Focus Endurance",
    "skills.name.cognitive-recovery": "Cognitive Recovery",
    "skills.name.planning-sequencing": "Planning & Sequencing",
    "skills.name.deadline-calibration": "Deadline Calibration",

    // skill tree — page chrome
    "skills.treeSubtitle": "Master skills from the bottom up. Each skill builds on the ones below it.",
    "skills.unlockInfoPre": "Skills unlock when their prerequisites reach",
    "skills.unlockInfoPost": "or better — completed via a 3-week training cycle with a stability score ≥ 70%. Progress is based on your check-in patterns, not a timer.",
    "skills.taskPlaceholder": "e.g., At 8am at my desk, I will open my textbook",

    // weekly trend
    "dashboard.weeklyTrend": "2-Week Trend",
    "checkin.focus.noCheckIn": "No check-in",
    "checkin.didNotStudy": "Did not study",

    // settings — coaching prefs
    "settings.coachingPrefs": "Coaching Preferences",
    "settings.coachingStyle": "Coaching style",
    "settings.styleDirect": "Direct",
    "settings.styleSocratic": "Socratic",
    "settings.styleDirectDesc": "Coach gives clear feedback and suggestions.",
    "settings.styleSocraticDesc": "Coach asks questions to help you think it through yourself.",
    "settings.motivation": "What drives you?",
    "settings.motivationIntrinsic": "Genuine understanding",
    "settings.motivationExam": "Grades & exams",
    "settings.phoneScreenTime": "Average daily phone screen time (hours)",
    "settings.phoneScreenTimeDesc": "Helps the coach understand your distraction environment.",
    "settings.savePrefs": "Save preferences",
    "settings.prefsSaved": "Saved",

    // settings — calendar sync
    "settings.calendarSync": "Calendar Sync",
    "settings.calendarDesc": "Paste your calendar's private iCal feed URL to import upcoming events automatically. Works with",
    "settings.calendarDescSuffix": "and any app that exports .ics feeds.",
    "settings.calendarHowToTitle": "How to get your feed URL",
    "settings.calendarGoogleHint": "Google Calendar: Settings → your calendar → \"Secret address in iCal format\"",
    "settings.calendarBlackboardHint": "Blackboard: Calendar → Export / Feed",
    "settings.calendarCanvasHint": "Canvas: Calendar → Calendar Feed (bottom left)",
    "settings.calendarSyncBtn": "Sync",
    "settings.calendarResync": "Re-sync",
    "settings.calendarSyncing": "Syncing…",
    "settings.calendarDisconnect": "Disconnect calendar",
    "settings.calendarLastSynced": "Last synced:",
    "settings.calendarUrlPlaceholder": "https://calendar.google.com/calendar/ical/...",
    "settings.calendarImportedPre": "Imported",
    "settings.calendarImportedEvent": "event",
    "settings.calendarImportedEvents": "events",
    "settings.calendarAlreadyExisted": "already existed",

    // tools page
    "tools.title": "AI Study Tools",
    "tools.subtitle": "Curated tools to complement your skill training. Use them alongside your daily sessions.",
    "tools.basedOnProfile": "Based on your profile, tools for your",
    "tools.dimensionHighlighted": "dimension are highlighted.",
    "tools.recommendedForYou": "Recommended for you",
    "tools.studyfetch.desc": "Transforms your notes and files into flashcards, quizzes, podcasts, and personalised study plans.",
    "tools.studyfetch.when": "Use when you need to memorise course material or want active recall practice.",
    "tools.notebooklm.desc": "Upload lecture notes and get audio summaries, mind maps, and a Q&A assistant grounded in your material.",
    "tools.notebooklm.when": "Use when you want to deeply understand a topic or need a structured summary before an exam.",
    "tools.napkin.desc": "Paste any text and Napkin auto-generates visual mind maps and diagrams to help you see connections.",
    "tools.napkin.when": "Use when your notes feel disorganised or you want to visualise a concept.",
    "tools.consensus.desc": "AI-powered research engine that finds answers from peer-reviewed papers — evidence-based, not opinion.",
    "tools.consensus.when": "Use when you want to verify a study strategy or understand research behind a topic.",
    "tools.magicschool.desc": "Generates practice quizzes, rubrics, and study prompts. Great for self-assessment before exams.",
    "tools.magicschool.when": "Use when you want to test yourself with a mock quiz or simulate exam conditions.",
  },
  ar: {
    // Legacy top-level keys (Sidebar uses these)
    dashboard: "لوحة التحكم",
    checkIn: "تسجيل اليوم",
    skills: "المهارات",
    aiCoach: "المدرب الذكي",
    tools: "أدوات الذكاء",
    events: "الأحداث",
    history: "السجل",
    settings: "الإعدادات",
    signOut: "تسجيل الخروج",
    "feedback.button": "إرسال ملاحظة",
    "feedback.title": "إرسال ملاحظة",
    "feedback.description": "لديك اقتراح أو وجدت خطأً أو تريد قول شيء؟ نقرأ كل شيء.",
    "feedback.placeholder": "اكتب ملاحظتك هنا…",
    "feedback.submit": "إرسال",
    "feedback.sending": "جارٍ الإرسال…",
    "feedback.sent": "تم إرسال الملاحظة — شكراً!",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    arabic: "العربية",
    english: "English",

    // nav.*
    "nav.dashboard": "لوحة التحكم",
    "nav.checkIn": "تسجيل اليوم",
    "nav.skills": "المهارات",
    "nav.aiCoach": "المدرب الذكي",
    "nav.events": "الأحداث",
    "nav.history": "السجل",
    "nav.settings": "الإعدادات",
    "nav.signOut": "تسجيل الخروج",

    // common.*
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.submit": "إرسال",
    "common.skip": "تخطي",
    "common.continue": "متابعة",
    "common.loading": "جاري التحميل...",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.add": "إضافة",
    "common.close": "إغلاق",
    "common.open": "فتح",
    "common.optional": "(اختياري)",

    // dashboard.*
    "dashboard.todayNote": "ملاحظة اليوم",
    "dashboard.recentPerformance": "الأداء الأخير",
    "dashboard.coach": "المدرب",
    "dashboard.openFullChat": "فتح المحادثة الكاملة",
    "dashboard.messageCoach": "أرسل رسالة لمدربك",
    "dashboard.observationInProgress": "المراقبة جارية",
    "dashboard.noActiveSkill": "لا توجد مهارة نشطة",
    "dashboard.skillOverview": "نظرة عامة على المهارات",
    "dashboard.observationMode": "أنت في وضع المراقبة",
    "dashboard.talkToCoach": "تحدث مع المدرب",
    "dashboard.addPersonalStatement": "أضف تأكيدك الشخصي",
    "dashboard.currentPlan": "الخطة الحالية",
    "dashboard.skillTree": "شجرة المهارات",
    "dashboard.yourTask": "مهمتك",
    "dashboard.noTaskDefined": "لم يتم تحديد مهمة بعد",
    "dashboard.workingAround": "التحديات:",
    "dashboard.setTaskInSkillPage": "حددها في صفحة المهارات",
    "dashboard.dailyCheckIn": "تسجيل اليومي",
    "dashboard.completedToday": "تم اليوم",
    "dashboard.startCheckIn": "ابدأ التسجيل",
    "dashboard.last7days": "آخر 7 أيام",
    "dashboard.7dAgo": "منذ 7 أيام",
    "dashboard.today": "اليوم",
    "dashboard.upcomingEvents": "الأحداث القادمة",
    "dashboard.noUpcomingEvents": "لا توجد أحداث قادمة",
    "dashboard.askCoachAnything": "اسأل مدربك أي شيء…",

    // checkin.*
    "checkin.title": "تسجيل اليومي",
    "checkin.didYouStudy": "هل درست اليوم؟",
    "checkin.howWasFocus": "كيف كان تركيزك؟",
    "checkin.whyDidYouMiss": "لماذا فاتك الدراسة؟",
    "checkin.whatMethod": "ما الطريقة التي استخدمتها؟",
    "checkin.anythingToNote": "هل هناك ما تريد ملاحظته؟",
    "checkin.quickReflection": "تأمل سريع",
    "checkin.markAtypical": "وضع علامة على يوم غير عادي (مرض، سفر، إلخ)",
    "checkin.energy": "الطاقة",
    "checkin.mood": "المزاج",
    "checkin.submitCheckIn": "إرسال التسجيل",
    "checkin.submitting": "جاري الإرسال...",
    "checkin.contextPlaceholder": "سياق سريع عن يومك...",
    "checkin.answerPlaceholder": "إجابتك...",
    "checkin.skipAndSubmit": "تخطي وإرسال",
    "checkin.optional": "(اختياري)",
    "checkin.energyOptional": "الطاقة (اختياري)",
    "checkin.moodOptional": "المزاج (اختياري)",
    "checkin.continueArrow": "متابعة ←",
    "checkin.whatHappened": "ماذا حدث؟",
    "checkin.atypicalHint": "مرض، سفر، إلخ",

    // focus options
    "checkin.focus.none": "لا يوجد",
    "checkin.focus.brief": "مختصر",
    "checkin.focus.focused": "مركّز",
    "checkin.focus.deep": "عميق",
    "checkin.focus.noneDesc": "لم أركز فعلاً",
    "checkin.focus.briefDesc": "بضع دقائق تركيز",
    "checkin.focus.focusedDesc": "كتلة تركيز جيدة",
    "checkin.focus.deepDesc": "تركيز عميق ممتد",

    // miss reason options
    "checkin.miss.tooBusy": "مشغول جداً",
    "checkin.miss.forgot": "نسيت",
    "checkin.miss.overwhelmed": "شعرت بالإرهاق",
    "checkin.miss.notInMood": "لم أكن في المزاج",
    "checkin.miss.externalEvent": "حدث خارجي",
    "checkin.miss.other": "أخرى",

    // study method options
    "checkin.method.explain": "شرحته بصوت عالٍ",
    "checkin.method.qa": "أسئلة تدريبية / سؤال وجواب",
    "checkin.method.mindmap": "خريطة ذهنية",
    "checkin.method.notes": "كتبت ملاحظات",
    "checkin.method.record": "تسجيل صوتي / فيديو",
    "checkin.method.read": "قراءة / مشاهدة",

    // decay options
    "checkin.decay.noLoss": "لا انخفاض",
    "checkin.decay.whenDropped": "متى انخفض تركيزك؟",

    // skills.*
    "skills.week1Label": "الأسبوع 1 — استقرار",
    "skills.week2Label": "الأسبوع 2 — تعبير",
    "skills.week3Label": "الأسبوع 3 — استكشاف",
    "skills.week1Short": "استقرار",
    "skills.week2Short": "تعبير",
    "skills.week3Short": "استكشاف",
    "skills.tier": "المستوى",
    "skills.active": "نشط",
    "skills.locked": "مقفل",
    "skills.available": "متاح",
    "skills.stable": "مستقر",
    "skills.mastered": "متقن",
    "skills.stability": "الاستقرار",
    "skills.prerequisites": "المتطلبات",
    "skills.weekPhase": "مرحلة الأسبوع",
    "skills.cycleProgress": "تقدم الدورة",
    "skills.stabilityScore": "درجة الاستقرار",
    "skills.yourTask": "مهمتك",
    "skills.notStarted": "لم يبدأ",
    "skills.ready": "جاهز",
    "skills.description": "الوصف",
    "skills.whyThisSkill": "لماذا هذه المهارة؟",
    "skills.trainingProgress": "تقدم التدريب",
    "skills.checkIns": "تسجيلات",
    "skills.daysStudied": "أيام الدراسة",
    "skills.focusedDays": "أيام التركيز",
    "skills.finalStability": "الاستقرار النهائي",
    "skills.totalCheckIns": "مجموع التسجيلات",
    "skills.generateNarrative": "توليد ملخص النمو",
    "skills.narrativeGenerating": "جاري التوليد...",
    "skills.narrativeError": "تعذّر توليد الملخص. حاول مجددًا.",
    "skills.trainingTimeline": "الجدول الزمني للتدريب",
    "skills.defineTask": "حدد مهمتك (وقت / مكان / فعل)",
    "skills.setTask": "تعيين المهمة",
    "skills.saving": "جاري الحفظ...",
    "skills.activating": "جاري التفعيل...",
    "skills.activateSkill": "تفعيل هذه المهارة",
    "skills.backToSkillTree": "العودة إلى شجرة المهارات",
    "skills.requiredToUnlock": "مطلوب لفتح القفل",
    "skills.completeFirst": "أكمل أولاً",
    "skills.requires": "يتطلب",
    "skills.unlocks": "يفتح",
    "skills.viewFullDetails": "عرض التفاصيل الكاملة",
    "skills.whyThisSkillLabel": "لماذا هذه المهارة؟",
    "skills.status": "الحالة",
    "skills.week": "الأسبوع",
    "skills.taskUsed": "المهمة المستخدمة",
    "skills.prerequisiteNote": "يجب أن يصل كل متطلب إلى مستقر — مكتمل بالمرور بدورة التدريب المكونة من 3 أسابيع بدرجة استقرار 70٪ أو أعلى. يعتمد التقدم على أنماط تسجيلاتك.",
    "skills.skillIsLocked": "هذه المهارة مقفلة",
    "skills.needsPlanning": "← يحتاج التخطيط أولاً",

    // chat.*
    "chat.placeholder": "أرسل رسالة...",
    "chat.send": "إرسال",
    "chat.title": "تحدث مع مدربك الذكي للدراسة",
    "chat.askCoach": "اسأل مدربك للدراسة...",
    "chat.aiStudyCoach": "مدربك الذكي للدراسة",
    "chat.coachDescription": "اسأل عن تقدمك، واحصل على نصائح حول مهارتك النشطة، أو تحدث عن كيفية سير الدراسة.",

    // events.*
    "events.addEvent": "إضافة حدث",
    "events.eventName": "اسم الحدث",
    "events.type": "النوع",
    "events.date": "التاريخ",
    "events.noUpcoming": "لا توجد أحداث قادمة",
    "events.upcoming": "القادمة",
    "events.passed": "المنتهية",
    "events.upcomingEvents": "الأحداث القادمة",
    "events.daysAway": "أيام متبقية",
    "events.today": "اليوم",
    "events.tomorrow": "غداً",
    "events.exam": "امتحان",
    "events.quiz": "اختبار",
    "events.deadline": "موعد نهائي",
    "events.project": "مشروع",
    "events.other": "أخرى",
    "events.loadingEvents": "جاري تحميل الأحداث...",
    "events.title": "الأحداث",
    "events.add": "إضافة",
    "events.cancel": "إلغاء",
    "events.namePlaceholder": "مثال: الامتحان النهائي",

    // history.*
    "history.title": "سجل الدراسة",
    "history.studied": "درست",
    "history.missed": "فاتني",
    "history.focused": "مركّز",
    "history.checkInHistory": "سجل التسجيلات",
    "history.trackPatterns": "تتبع أنماط دراستك عبر الزمن.",
    "history.checkIns30d": "التسجيلات (30 يوم)",
    "history.daysStudied": "أيام الدراسة",
    "history.focusedPlusDays": "أيام التركيز+",
    "history.noFocus": "لا تركيز",
    "history.brief": "مختصر",
    "history.deep": "عميق",
    "history.focusLevel": "مستوى التركيز",
    "history.focusDecay": "انخفاض التركيز",
    "history.energy": "الطاقة",
    "history.mood": "المزاج",
    "history.note": "ملاحظة",
    "history.atypical": "غير عادي",
    "history.backfilled": "مُعبأ لاحقاً",

    // settings.*
    "settings.title": "الإعدادات",
    "settings.account": "الحساب",
    "settings.email": "البريد الإلكتروني",
    "settings.name": "الاسم",
    "settings.notSet": "غير محدد",
    "settings.actions": "الإجراءات",
    "settings.appearance": "المظهر",
    "settings.accentColor": "لون التمييز",
    "settings.saving": "جاري الحفظ…",
    "settings.signOut": "تسجيل الخروج",

    // auth.*
    "auth.signInToAccount": "سجّل الدخول إلى حسابك",
    "auth.emailAddress": "عنوان البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.signIn": "تسجيل الدخول",
    "auth.createAccount": "إنشاء حساب",
    "auth.fullName": "الاسم الكامل",
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.resetPassword": "إعادة تعيين كلمة المرور",
    "auth.sendResetLink": "إرسال رابط الإعادة",
    "auth.backToSignIn": "العودة إلى تسجيل الدخول",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.signUp": "التسجيل",
    "auth.signingIn": "جاري تسجيل الدخول...",
    "auth.creatingAccount": "جاري إنشاء الحساب...",
    "auth.sending": "جاري الإرسال...",
    "auth.welcomeBack": "مرحباً بعودتك",
    "auth.continueJourney": "سجّل دخولك لمتابعة رحلتك الدراسية",
    "auth.startHabits": "ابدأ في بناء عادات دراسية أفضل",
    "auth.email": "البريد الإلكتروني",
    "auth.name": "الاسم",
    "auth.rememberMe": "تذكرني",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.register": "التسجيل",
    "auth.alreadyHaveAccountQ": "لديك حساب بالفعل؟",
    "auth.signInLink": "تسجيل الدخول",
    "auth.checkEmailForReset": "تحقق من بريدك الإلكتروني لرابط الإعادة",
    "auth.enterEmailForReset": "أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور",
    "auth.resetLinkSent": "إذا كان الحساب موجوداً، فقد أرسلنا رابط الإعادة.",
    "auth.resendEmail": "إعادة إرسال البريد",
    "auth.backToLogin": "العودة إلى تسجيل الدخول",
    "auth.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",

    // onboarding.*
    "onboarding.studyGoalTitle": "ما الذي تسعى إليه؟",
    "onboarding.studyGoalLabel": "هدفك الدراسي",
    "onboarding.studyGoalPlaceholder": "مثال: اجتياز الكيمياء العضوية، تحسين المعدل...",
    "onboarding.hoursLabel": "كم ساعة تدرس عادةً في اليوم؟",
    "onboarding.hoursPlaceholder": "مثال: 2",
    "onboarding.challengesTitle": "ما الذي يعيقك أكثر؟",
    "onboarding.challengesSubtitle": "اختر كل ما ينطبق.",
    "onboarding.challengePlaceholder": "صف تحديك...",
    "onboarding.timeTitle": "متى تدرس عادةً؟",
    "onboarding.eventTitle": "حدث أكاديمي قادم",
    "onboarding.eventSubtitle": "أضف امتحاناً أو اختباراً أو موعداً نهائياً لتأطير تدريبك.",
    "onboarding.eventNameLabel": "اسم الحدث",
    "onboarding.eventNamePlaceholder": "مثال: امتحان منتصف الفصل",
    "onboarding.eventDateLabel": "التاريخ",
    "onboarding.eventTypeLabel": "النوع",
    "onboarding.startObservation": "بدء مرحلة المراقبة",
    "onboarding.settingUp": "جاري الإعداد...",
    "onboarding.skipEvent": "تخطي الحدث الآن",
    "onboarding.back": "رجوع",
    "onboarding.challenge.starting": "البدء هو الأصعب",
    "onboarding.challenge.distracted": "أتشتت بسهولة",
    "onboarding.challenge.nothingSticks": "أدرس لكن لا شيء يترسخ",
    "onboarding.challenge.cantFocus": "لا أستطيع التركيز طويلاً",
    "onboarding.challenge.procrastinate": "أؤجل حتى اللحظة الأخيرة",
    "onboarding.challenge.dontKnowWhat": "لا أعرف من أين أبدأ",
    "onboarding.challenge.other": "أخرى",
    "onboarding.time.earlyMorning": "الصباح الباكر",
    "onboarding.time.lateMorning": "منتصف الصباح",
    "onboarding.time.afternoon": "بعد الظهر",
    "onboarding.time.evening": "المساء",
    "onboarding.time.lateNight": "آخر الليل",
    "onboarding.time.varies": "يتفاوت من يوم لآخر",

    // dashboard extra strings
    "dashboard.observationText": "ادرس كما تفعل عادةً وسجّل تسجيلاتك اليومية. بعد 5 تسجيلات أو أكثر سنفتح لك مهارتك الأولى.\nإذا لاحظت أنماطاً — تشتت، طاقة منخفضة، صعوبة في البدء — تحدث مع مدربك عنها الآن.",
    "dashboard.completeCheckins": "أكمل تسجيلاتك اليومية. بعد 5 تسجيلات في 7 أيام ستفتح مهارتك الأولى.",
    "dashboard.visitSkillsPage": "لم تفعّل مهارة بعد. اذهب إلى صفحة المهارات، اختر مهارة وفعّلها لتبدأ التدريب.",

    // chat errors
    "chat.errorSend": "فشل إرسال الرسالة",
    "chat.errorFallback": "عذراً، حدث خطأ ما. يرجى المحاولة مجدداً.",

    // notifications
    "notifications.title": "الإشعارات",
    "notifications.allCaughtUp": "أنت على اطلاع بكل شيء",
    "notifications.pushEnable": "تفعيل الإشعارات",
    "notifications.pushDisable": "إيقاف الإشعارات",
    "notifications.pushDenied": "الإشعارات محظورة في إعدادات المتصفح",
    "notifications.pushLoading": "جارٍ التحديث…",

    // dimension profile
    "dimension.profileTitle": "أبعاد المهارات",
    "dimension.behavioral": "السلوكي",
    "dimension.cognitive": "المعرفي",
    "dimension.metacognitive": "ما وراء المعرفة",
    "dimension.notYet": "لم يبدأ بعد",
    "dimension.early": "بداية",
    "dimension.developing": "في تطور",
    "dimension.strong": "قوي",
    "dimension.mastered": "متقن",
    "dimension.whatAreThese": "ما هذه؟",
    "dimension.behavioralDesc": "مدى التزامك بالحضور. المهارات: وضوح المهمة، البدء.",
    "dimension.cognitiveDesc": "ما يحدث خلال الجلسة — عمق التركيز وإدارة البيئة. المهارات: احتواء التركيز، التحكم في البيئة، تحمل التركيز، التعافي المعرفي.",
    "dimension.metacognitiveDesc": "كيف تخطط قبل الجلسة وتراجع بعدها. المهارات: التخطيط والتسلسل، معايرة المواعيد.",

    // banner
    "dashboard.addBannerPhoto": "أضف صورة غلاف",
    "dashboard.bannerUrlPlaceholder": "الصق رابط الصورة...",
    "dashboard.removeBanner": "إزالة",
    "dashboard.repositionBanner": "إعادة تحديد موضع الصورة",
    "dashboard.dragToReposition": "اسحب لإعادة الضبط",
    "dashboard.savePosition": "حفظ الموضع",
    "dashboard.personalStatementPlaceholder": "تأكيدك الشخصي…",

    // backfill
    "checkin.differentDay": "يوم مختلف؟",
    "checkin.checkingInFor": "تسجيل ليوم:",
    "checkin.today": "اليوم",
    "checkin.yesterday": "أمس",
    "checkin.twoDaysAgo": "منذ يومين",
    "checkin.threeDaysAgo": "منذ 3 أيام",
    "checkin.alreadyCheckedIn": "لقد سجّلت بالفعل لهذا اليوم.",
    "checkin.fullSession": "نعم، جلسة كاملة",
    "checkin.briefly": "لفترة قصيرة (أقل من 15 دقيقة)",
    "checkin.intentionLabel": "ماذا تخطط للدراسة؟",
    "checkin.intentionPlaceholder": "مثال: ملخص الفصل الثالث، 30 دقيقة...",
    "checkin.intentionSkip": "تخطي",

    // plan card instructions
    "plan.week1Instruction": "ركّز فقط على الحضور المنتظم. لا تسعَ للكمال — ابنِ الروتين أولاً.",
    "plan.week2Instruction": "لقد حضرت. الآن انتبه للجودة. جرّب تعديلات صغيرة في تطبيق المهارة.",
    "plan.week3Instruction": "طبّق المهارة في مواقف أصعب. لاحظ متى تنهار — هذا بيانات مفيدة، ليس فشلاً.",

    // phase / observation
    "phase.observation": "مرحلة المراقبة",
    "phase.skill_training": "تدريب المهارات",
    "phase.onboarding": "الإعداد",
    "phase.day": "يوم",
    "phase.activeLabel": "نشط:",
    "phase.checkIns": "تسجيلات",
    "phase.completeCheckIns": "أكمل تسجيلاتك اليومية",

    // skill tree — tier labels
    "skills.tier.1": "الأساس",
    "skills.tier.2": "الهيكل",
    "skills.tier.3": "التحمّل",
    "skills.tier.4": "الإتقان",

    // skill tree — skill names
    "skills.name.task-clarity": "وضوح المهمة",
    "skills.name.initiation": "البدء",
    "skills.name.focus-containment": "احتواء التركيز",
    "skills.name.environment-control": "التحكم في البيئة",
    "skills.name.focus-endurance": "تحمّل التركيز",
    "skills.name.cognitive-recovery": "التعافي المعرفي",
    "skills.name.planning-sequencing": "التخطيط والتسلسل",
    "skills.name.deadline-calibration": "معايرة المواعيد",

    // skill tree — page chrome
    "skills.treeSubtitle": "أتقن المهارات من الأساس للأعلى. كل مهارة تبني على ما قبلها.",
    "skills.unlockInfoPre": "تُفتح المهارات عندما تصل متطلباتها إلى",
    "skills.unlockInfoPost": "أو أعلى — عبر دورة تدريب 3 أسابيع بدرجة استقرار ≥ 70٪. يعتمد التقدم على أنماط تسجيلاتك.",
    "skills.taskPlaceholder": "مثال: في الساعة 8 صباحاً على مكتبي، سأفتح الكتاب",

    // weekly trend
    "dashboard.weeklyTrend": "اتجاه الأسبوعين",
    "checkin.focus.noCheckIn": "لا تسجيل",
    "checkin.didNotStudy": "لم أدرس",

    // settings — coaching prefs
    "settings.coachingPrefs": "تفضيلات التدريب",
    "settings.coachingStyle": "أسلوب التدريب",
    "settings.styleDirect": "مباشر",
    "settings.styleSocratic": "سقراطي",
    "settings.styleDirectDesc": "يقدم المدرب ملاحظات واضحة ومقترحات مباشرة.",
    "settings.styleSocraticDesc": "يطرح المدرب أسئلة تساعدك على التفكير بنفسك.",
    "settings.motivation": "ما الذي يحفزك؟",
    "settings.motivationIntrinsic": "الفهم الحقيقي",
    "settings.motivationExam": "الدرجات والامتحانات",
    "settings.phoneScreenTime": "متوسط وقت شاشة الهاتف اليومي (ساعات)",
    "settings.phoneScreenTimeDesc": "يساعد المدرب على فهم بيئة التشتت لديك.",
    "settings.savePrefs": "حفظ التفضيلات",
    "settings.prefsSaved": "تم الحفظ",

    // settings — calendar sync
    "settings.calendarSync": "مزامنة التقويم",
    "settings.calendarDesc": "الصق رابط تقويمك الخاص (iCal) لاستيراد الأحداث القادمة تلقائياً. يعمل مع",
    "settings.calendarDescSuffix": "وأي تطبيق يدعم تصدير .ics.",
    "settings.calendarHowToTitle": "كيف تحصل على رابط تقويمك",
    "settings.calendarGoogleHint": "Google Calendar: الإعدادات ← تقويمك ← \"عنوان سري بتنسيق iCal\"",
    "settings.calendarBlackboardHint": "Blackboard: التقويم ← تصدير / رابط التغذية",
    "settings.calendarCanvasHint": "Canvas: التقويم ← رابط التقويم (أسفل اليسار)",
    "settings.calendarSyncBtn": "مزامنة",
    "settings.calendarResync": "إعادة المزامنة",
    "settings.calendarSyncing": "جارٍ المزامنة…",
    "settings.calendarDisconnect": "فصل التقويم",
    "settings.calendarLastSynced": "آخر مزامنة:",
    "settings.calendarUrlPlaceholder": "https://calendar.google.com/calendar/ical/...",
    "settings.calendarImportedPre": "تم استيراد",
    "settings.calendarImportedEvent": "حدث",
    "settings.calendarImportedEvents": "أحداث",
    "settings.calendarAlreadyExisted": "موجودة مسبقاً",

    // tools page
    "tools.title": "أدوات الذكاء الاصطناعي للدراسة",
    "tools.subtitle": "أدوات منتقاة لتكمل تدريبك على المهارات. استخدمها إلى جانب جلساتك اليومية.",
    "tools.basedOnProfile": "بناءً على ملفك، الأدوات الخاصة ببُعد",
    "tools.dimensionHighlighted": "مميّزة لك.",
    "tools.recommendedForYou": "موصى به لك",
    "tools.studyfetch.desc": "تحوّل ملاحظاتك وملفاتك إلى بطاقات تعليمية واختبارات وبودكاست وخطط دراسية مخصصة.",
    "tools.studyfetch.when": "استخدمه عندما تحتاج لحفظ مادة الدراسة أو تريد ممارسة الاستدعاء النشط.",
    "tools.notebooklm.desc": "ارفع ملاحظات المحاضرات واحصل على ملخصات صوتية وخرائط ذهنية ومساعد أسئلة وأجوبة.",
    "tools.notebooklm.when": "استخدمه عندما تريد فهماً عميقاً لموضوع أو تحتاج ملخصاً منظماً قبل الامتحان.",
    "tools.napkin.desc": "الصق أي نص وسيولّد Napkin خرائط ذهنية ومخططات بصرية تساعدك على رؤية الروابط.",
    "tools.napkin.when": "استخدمه عندما تبدو ملاحظاتك غير منظمة أو تريد تصوير مفهوم بصرياً.",
    "tools.consensus.desc": "محرك بحث بالذكاء الاصطناعي يجد إجابات من الأوراق العلمية المحكّمة — مبني على الأدلة.",
    "tools.consensus.when": "استخدمه للتحقق من استراتيجية دراسية أو فهم الأبحاث وراء موضوع ما.",
    "tools.magicschool.desc": "يولّد اختبارات تدريبية ومعايير تقييم وتلميحات دراسية. مثالي للتقييم الذاتي قبل الامتحانات.",
    "tools.magicschool.when": "استخدمه عندما تريد اختبار نفسك باختبار وهمي أو محاكاة ظروف الامتحان.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Lang | null;
    if (saved === "ar" || saved === "en") {
      applyLang(saved);
      setLangState(saved);
    }
  }, []);

  const applyLang = (l: Lang) => {
    document.documentElement.lang = l;
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
  };

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
    applyLang(l);
  };

  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
